In [ ]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.__version__)

1.26.4


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]   ndim=2)
print()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-26-762d44395c8d>, line 1)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:


a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])


1


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  8


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1, 1, 0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
10


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:


arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:3])



[1 2 3]


In [ ]:
# arr = np.array([1, 2, 3, 4])

arr2=np.array([0.1, 2.9, 3.6, 40.3])
print(arr2.dtype)


# print(arr.dtype)

float64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
arr3 = np.array(['w', 'b', 'y'])

print(arr.dtype)
print(arr3.dtype)

<U6
<U1


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42 20 30 40 50]
[42 20 30 40 50]


In [ ]:
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])






newarr = arr.reshape(4, 3)
print(newarr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 22,],[34, 3,],ndim=2)

print(arr)
print('shape of array :', arr.shape)

TypeError: array() got an unexpected keyword argument 'ndim'

In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))
arr = np.concatenate((arr1, arr2))

arr3 = np.concatenate((arr1, arr2),axis=1)
arr2 = np.concatenate((arr1, arr2),axis=0)


# print(arr1)
# print(arr2)
# print(arr3)
print(arr3)
print(arr2)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [ ]:

np.arange(8).reshape(2,2,2)



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((20,30))

array([[0.27018742, 0.29195282, 0.74118774, 0.19183376, 0.55210333,
        0.54428039, 0.55248731, 0.12152935, 0.45980597, 0.20271429,
        0.3348168 , 0.82733182, 0.50267544, 0.92135447, 0.34410987,
        0.02847746, 0.97618877, 0.4662026 , 0.18088132, 0.23366121,
        0.89149923, 0.15659494, 0.88509553, 0.62107157, 0.04180788,
        0.13522999, 0.15109225, 0.3487788 , 0.68480038, 0.6792341 ],
       [0.80949209, 0.14593699, 0.95701862, 0.55805854, 0.25574341,
        0.89932951, 0.99077244, 0.79019889, 0.45554099, 0.9403405 ,
        0.32881165, 0.07873276, 0.603398  , 0.3365007 , 0.24798296,
        0.0334235 , 0.45918381, 0.41966473, 0.84479427, 0.19655495,
        0.70890361, 0.42642126, 0.03691027, 0.68006296, 0.71230957,
        0.7269846 , 0.72183853, 0.62519827, 0.78434948, 0.45339557],
       [0.26853259, 0.20522075, 0.41288547, 0.00489301, 0.41809095,
        0.07709922, 0.35208131, 0.6599761 , 0.69706952, 0.8693808 ,
        0.64953019, 0.04221908, 0.82320731, 0.

In [ ]:
np.linspace(-10,10,10 ,dtype=int)



array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.ndim

3

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(a3.dtype)

int64


In [ ]:
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a3 ** 2

array([[[ 0,  1],
        [ 4,  9]],

       [[16, 25],
        [36, 49]]])

In [ ]:
a3 == 15

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[100.,   1.,  26.],
       [ 85.,  56.,  97.],
       [ 88.,  65.,  43.]])

In [ ]:
np.sin(a1)

array([[-0.50636564,  0.84147098,  0.76255845],
       [-0.17607562, -0.521551  ,  0.37960774],
       [ 0.0353983 ,  0.82682868, -0.83177474]])

In [ ]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
arr = np.array([10, 20, 3])
np.exp(arr)


array([2.20264658e+04, 4.85165195e+08, 2.00855369e+01])

In [ ]:

np.ceil(np.random.random((2,3))*100)

array([[53., 17., 89.],
       [61., 95., 25.]])

In [ ]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])